# Generated by Django 2.1.4 on 2020-03-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200301_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='base_blog',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
    ]
