# Generated by Django 2.1.4 on 2020-03-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200301_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='base_blog',
            new_name='blog',
        ),
    ]
