# Generated by Django 2.1.4 on 2020-03-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200301_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='discuss',
        ),
    ]
