# Generated by Django 2.1.4 on 2020-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200302_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classes2',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classes3',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
